# Generated by Django 2.2.28 on 2023-11-30 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20231130_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 1, 0, 20, 41, 942628), verbose_name='Опубликована'),
        ),
    ]
